apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patches:
  # Add unique label to StatefulSet pod template
  - path: statefulset-label.yaml
    target:
      kind: StatefulSet
      name: postgresql
  # Add the same label to regular service selector to make it unique
  - path: service-selector.yaml
    target:
      kind: Service
      name: postgresql
